version: "3.5"
services:
  demo:
    build:
      context: ./
    volumes:
      - ./src:/src
    networks:
    - services
    ports: 
      - 80:8080
      - 40000:40000
networks:
  services:
    external: true