version: "3.5"
services:
  demo:
    env_file: env/.env
    build:
      context: ./
    volumes:
      - ./src:/src
    networks:
    - services
    ports:
      - 8888:8888
      - 40000:40000
networks:
  services:
    external: true